resolver: lts-5.14
image:
  containers:
    - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
      name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
- hpack-0.12.0
- path-io-1.1.0
apply-ghc-options: locals
